# F:/Repo/timetagger-super-status/docker-compose.yml
version: "3.8"

services:
  super-status:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/root/_timetagger/users/test~dGVzdA==.db
    volumes:
      - timetagger_db_volume:/root/_timetagger
volumes:
  timetagger_db_volume: # Volume key
    name: timetagger_shared_db_volume # Volume shared with timetagger
    external: true # Create no new volume