version: "3"
services:
  super-status:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_PATH=/root/_timetagger/users/test~dGVzdA==.db
    volumes:
      - timetagger-test-volume:/root/_timetagger

volumes:
  timetagger-test-volume:
    external: true